# GNU GENERAL PUBLIC LICENSE
# Version 3, 29 June 2007
#
# Copyright (C) 2025 authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
name: 'PullHero Consult'
description: 'A Python-based Consulting assistant'
author: 'PullHero'
branding:
  icon: message-square
  color: blue
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  api-key:
    description: 'API key for DeepSeek/OpenAI'
    required: true
  api-host:
    description: 'AI provider (deepseek/openai)'
    default: 'api.openai.com'
    required: true
  api-model:
    description: 'Model name'
    default: 'gpt-4-turbo'
    required: true
  model-digest-length:
    description: 'Max digest length'
    default: '4096'
    required: false
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.api-key }}
    - ${{ inputs.api-host }}
    - ${{ inputs.api-model }}
    - ${{ inputs.model-digest-length }}
